/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'project-categories': ProjectCategory;
    projects: Project;
    partners: Partner;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'tj') | ('ru' | 'tj')[];
  globals: {
    'site-settings': SiteSetting;
    'contact-info': ContactInfo;
    navigation: Navigation;
    'seo-defaults': SeoDefault;
    'home-page': HomePage;
    'studio-page': StudioPage;
    'contact-page': ContactPage;
    'work-page': WorkPage;
    'project-detail-settings': ProjectDetailSetting;
    'contact-form-settings': ContactFormSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'studio-page': StudioPageSelect<false> | StudioPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'work-page': WorkPageSelect<false> | WorkPageSelect<true>;
    'project-detail-settings': ProjectDetailSettingsSelect<false> | ProjectDetailSettingsSelect<true>;
    'contact-form-settings': ContactFormSettingsSelect<false> | ContactFormSettingsSelect<true>;
  };
  locale: 'ru' | 'tj';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  orientation?: ('landscape' | 'portrait' | 'square') | null;
  photographer?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * One-line editorial project positioning.
   */
  tagline?: string | null;
  category: number | ProjectCategory;
  /**
   * Legacy display location. Prefer City and Country for new content.
   */
  location?: string | null;
  city?: string | null;
  country?: string | null;
  year?: number | null;
  status?: ('built' | 'concept' | 'in-progress' | 'completed') | null;
  buildingType?: ('residential' | 'interior' | 'architecture' | 'hospitality') | null;
  services?: ('architecture' | 'interior-design' | 'master-planning' | 'furniture-design' | 'landscape')[] | null;
  area?: string | null;
  architect?: string | null;
  client?: string | null;
  photographer?: string | null;
  /**
   * Select a project-specific Media item. Replacing the file inside a shared Media item changes every project that references it.
   */
  coverImage: number | Media;
  gallery?:
    | {
        /**
         * Use a unique Media item for each gallery image. Replacing a shared Media file updates every field that references it.
         */
        image: number | Media;
        caption?: string | null;
        altText?: string | null;
        orientation?: ('landscape' | 'portrait' | 'square') | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short editorial summary for listing and featured project contexts.
   */
  excerpt?: string | null;
  /**
   * 40-60 word editorial summary for CMS/content planning.
   */
  summary?: string | null;
  /**
   * Longer project description for future project detail pages.
   */
  description?: string | null;
  /**
   * Legacy excerpt field. Prefer Excerpt for new content.
   */
  shortDescription?: string | null;
  concept?: string | null;
  lightingConcept?: string | null;
  spatialQualities?: string | null;
  photographyDirection?: string | null;
  materials?: string | null;
  credits?: string | null;
  featured?: boolean | null;
  published?: boolean | null;
  order?: number | null;
  relatedProjects?: (number | Project)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Homepage partner rail. An uploaded Media logo replaces the selected Logoipsum placeholder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Used as accessible text when the visual logo has no readable wordmark.
   */
  name: string;
  /**
   * Optional. Upload or select the real partner logo here; it takes priority over the placeholder.
   */
  logo?: (number | null) | Media;
  /**
   * Optional absolute URL beginning with https:// or http://.
   */
  website?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  projectType?: string | null;
  estimatedBudget?: string | null;
  timeline?: string | null;
  message: string;
  source?: string | null;
  status?: ('new' | 'reviewed' | 'replied' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  orientation?: T;
  photographer?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  category?: T;
  location?: T;
  city?: T;
  country?: T;
  year?: T;
  status?: T;
  buildingType?: T;
  services?: T;
  area?: T;
  architect?: T;
  client?: T;
  photographer?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        altText?: T;
        orientation?: T;
        order?: T;
        id?: T;
      };
  excerpt?: T;
  summary?: T;
  description?: T;
  shortDescription?: T;
  concept?: T;
  lightingConcept?: T;
  spatialQualities?: T;
  photographyDirection?: T;
  materials?: T;
  credits?: T;
  featured?: T;
  published?: T;
  order?: T;
  relatedProjects?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  projectType?: T;
  estimatedBudget?: T;
  timeline?: T;
  message?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  siteDescription?: string | null;
  /**
   * Editorial studio description for future global/page content integration.
   */
  studioDescription?: string | null;
  /**
   * Short footer studio description.
   */
  footerDescription?: string | null;
  copyright?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    keywords?: string[] | null;
  };
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  email: string;
  phone?: string | null;
  address?: string | null;
  googleMaps?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  behance?: string | null;
  pinterest?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        url: string;
        order?: number | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  defaultTitle: string;
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    label?: string | null;
    heading: string;
    supportingText?: string | null;
    image?: (number | null) | Media;
    locationLine?: string | null;
  };
  selectedProjects?: {
    label?: string | null;
    heading?: string | null;
    archiveLinkLabel?: string | null;
  };
  studioIntro?: {
    label?: string | null;
    statement?: string | null;
    body?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  featuredProject?: {
    label?: string | null;
    heading?: string | null;
    linkLabel?: string | null;
  };
  contact?: {
    label?: string | null;
    statement?: string | null;
    body?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    keywords?: string[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-page".
 */
export interface StudioPage {
  id: number;
  hero?: {
    label?: string | null;
    statement?: string | null;
  };
  philosophy?: {
    label?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    label?: string | null;
    statement?: string | null;
  };
  principles?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  information?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contactCta?: {
    label?: string | null;
    statement?: string | null;
    linkLabel?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    keywords?: string[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero?: {
    label?: string | null;
    statement?: string | null;
  };
  inquiry?: {
    label?: string | null;
    body?: string | null;
  };
  collaboration?: {
    label?: string | null;
    statement?: string | null;
  };
  closing?: {
    label?: string | null;
    statement?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    keywords?: string[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page".
 */
export interface WorkPage {
  id: number;
  hero?: {
    label?: string | null;
    title?: string | null;
    intro?: string | null;
    singularProjectLabel?: string | null;
    pluralProjectLabel?: string | null;
  };
  archive?: {
    ariaLabel?: string | null;
    emptyNumberLabel?: string | null;
    emptyLocationLabel?: string | null;
    emptyYearLabel?: string | null;
    emptyTitle?: string | null;
    plateLabel?: string | null;
    platePlaceholder?: string | null;
  };
  fallbacks?: {
    location?: string | null;
    year?: string | null;
    yearRange?: string | null;
    projectDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-detail-settings".
 */
export interface ProjectDetailSetting {
  id: number;
  labels?: {
    statement?: string | null;
    services?: string | null;
    area?: string | null;
    architect?: string | null;
    status?: string | null;
    materials?: string | null;
    nextProject?: string | null;
  };
  fallbacks?: {
    category?: string | null;
    location?: string | null;
    year?: string | null;
    description?: string | null;
  };
  serviceLabels?: {
    architecture?: string | null;
    interiorDesign?: string | null;
    masterPlanning?: string | null;
    furnitureDesign?: string | null;
    landscape?: string | null;
  };
  statusLabels?: {
    built?: string | null;
    completed?: string | null;
    concept?: string | null;
    inProgress?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-form-settings".
 */
export interface ContactFormSetting {
  id: number;
  labels?: {
    email?: string | null;
    city?: string | null;
    country?: string | null;
    name?: string | null;
    projectType?: string | null;
    estimatedBudget?: string | null;
    timeline?: string | null;
    message?: string | null;
    company?: string | null;
    submit?: string | null;
    studioInformation?: string | null;
  };
  messages?: {
    defaultNote?: string | null;
    success?: string | null;
    emailError?: string | null;
    requiredError?: string | null;
  };
  placeholders?: {
    message?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  siteDescription?: T;
  studioDescription?: T;
  footerDescription?: T;
  copyright?: T;
  logo?: T;
  favicon?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        keywords?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?: T;
  googleMaps?: T;
  instagram?: T;
  linkedin?: T;
  behance?: T;
  pinterest?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        order?: T;
        visible?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        heading?: T;
        supportingText?: T;
        image?: T;
        locationLine?: T;
      };
  selectedProjects?:
    | T
    | {
        label?: T;
        heading?: T;
        archiveLinkLabel?: T;
      };
  studioIntro?:
    | T
    | {
        label?: T;
        statement?: T;
        body?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  featuredProject?:
    | T
    | {
        label?: T;
        heading?: T;
        linkLabel?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        statement?: T;
        body?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-page_select".
 */
export interface StudioPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        statement?: T;
      };
  philosophy?:
    | T
    | {
        label?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        label?: T;
        statement?: T;
      };
  principles?:
    | T
    | {
        text?: T;
        id?: T;
      };
  information?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contactCta?:
    | T
    | {
        label?: T;
        statement?: T;
        linkLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        statement?: T;
      };
  inquiry?:
    | T
    | {
        label?: T;
        body?: T;
      };
  collaboration?:
    | T
    | {
        label?: T;
        statement?: T;
      };
  closing?:
    | T
    | {
        label?: T;
        statement?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        title?: T;
        intro?: T;
        singularProjectLabel?: T;
        pluralProjectLabel?: T;
      };
  archive?:
    | T
    | {
        ariaLabel?: T;
        emptyNumberLabel?: T;
        emptyLocationLabel?: T;
        emptyYearLabel?: T;
        emptyTitle?: T;
        plateLabel?: T;
        platePlaceholder?: T;
      };
  fallbacks?:
    | T
    | {
        location?: T;
        year?: T;
        yearRange?: T;
        projectDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-detail-settings_select".
 */
export interface ProjectDetailSettingsSelect<T extends boolean = true> {
  labels?:
    | T
    | {
        statement?: T;
        services?: T;
        area?: T;
        architect?: T;
        status?: T;
        materials?: T;
        nextProject?: T;
      };
  fallbacks?:
    | T
    | {
        category?: T;
        location?: T;
        year?: T;
        description?: T;
      };
  serviceLabels?:
    | T
    | {
        architecture?: T;
        interiorDesign?: T;
        masterPlanning?: T;
        furnitureDesign?: T;
        landscape?: T;
      };
  statusLabels?:
    | T
    | {
        built?: T;
        completed?: T;
        concept?: T;
        inProgress?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-form-settings_select".
 */
export interface ContactFormSettingsSelect<T extends boolean = true> {
  labels?:
    | T
    | {
        email?: T;
        city?: T;
        country?: T;
        name?: T;
        projectType?: T;
        estimatedBudget?: T;
        timeline?: T;
        message?: T;
        company?: T;
        submit?: T;
        studioInformation?: T;
      };
  messages?:
    | T
    | {
        defaultNote?: T;
        success?: T;
        emailError?: T;
        requiredError?: T;
      };
  placeholders?:
    | T
    | {
        message?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}